import path from "path";
import fs from "fs";
import os from "os";

/** Post-Bridge API base URL */
export const API_BASE = "https://api.post-bridge.com/v1";

/** Pipeline subdirectories where posts live */
export const PIPELINE_SUBDIRS = ["drafts", "published", "scheduled"];

/** Path to the local config file (auto-generated by `accounts` command) */
export const CONFIG_PATH = path.resolve(
  path.dirname(new URL(import.meta.url).pathname),
  "..",
  ".post-bridge.json"
);

/** Files to skip when scanning the pipeline directory */
export const SKIP_FILES = ["_TEMPLATE.md", "AGENTS.md"];

/** Default timezone for scheduling */
export const TIMEZONE = "America/Bogota";

/** Default posting time (HH:MM in local timezone) */
export const DEFAULT_POSTING_TIME = "08:00";

/** UTC offset for America/Bogota (COT = UTC-5, no DST) */
export const UTC_OFFSET = "-05:00";

// ---------------------------------------------------------------------------
// Pipeline directory resolution
// ---------------------------------------------------------------------------

/**
 * Resolve the pipeline directory using (in priority order):
 * 1. PIPELINE_DIR env var (explicit override)
 * 2. SECOND_BRAIN_PATH env var + /03_creating/pipeline
 * 3. ~/.config/second-brain/config.json vaultPath + /03_creating/pipeline
 * 4. Default: ~/Documents/Second_Brain/03_creating/pipeline
 */
export function getPipelineDir(): string {
  // 1. Explicit override
  if (process.env.PIPELINE_DIR) {
    return process.env.PIPELINE_DIR;
  }

  // 2. SECOND_BRAIN_PATH env var
  if (process.env.SECOND_BRAIN_PATH) {
    return path.join(process.env.SECOND_BRAIN_PATH, "03_creating", "pipeline");
  }

  // 3. Config file
  const configFile = path.join(os.homedir(), ".config", "second-brain", "config.json");
  if (fs.existsSync(configFile)) {
    try {
      const config = JSON.parse(fs.readFileSync(configFile, "utf-8"));
      if (config.vaultPath) {
        return path.join(config.vaultPath, "03_creating", "pipeline");
      }
    } catch {
      // Fall through to default
    }
  }

  // 4. Default
  return path.join(os.homedir(), "Documents", "Second_Brain", "03_creating", "pipeline");
}

// ---------------------------------------------------------------------------
// API Key
// ---------------------------------------------------------------------------

export function getApiKey(): string {
  const key = process.env.POST_BRIDGE_API_KEY;
  if (!key) {
    console.error("Error: POST_BRIDGE_API_KEY environment variable is not set.");
    console.error("Add it to ~/.secrets/.env and restart your shell.");
    process.exit(1);
  }
  return key;
}

// ---------------------------------------------------------------------------
// Local config (cached account IDs etc.)
// ---------------------------------------------------------------------------

export interface AccountInfo {
  id: number;
  username: string;
}

export interface LocalConfig {
  accounts: {
    twitter?: AccountInfo;
    linkedin?: AccountInfo;
  };
  timezone: string;
  defaultPostingTime: string;
}

export function loadConfig(): LocalConfig | null {
  if (!fs.existsSync(CONFIG_PATH)) return null;
  return JSON.parse(fs.readFileSync(CONFIG_PATH, "utf-8"));
}

export function saveConfig(config: LocalConfig): void {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2) + "\n");
}

export function requireConfig(): LocalConfig {
  const config = loadConfig();
  if (!config) {
    console.error("Error: No config found. Run `bun run accounts` first to discover social accounts.");
    process.exit(1);
  }
  return config;
}
